services:

  db:
    image: postgres:15.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

  backend:
    build:
      context: ./backend
      target: development
    depends_on:
      - db
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    # environment:
    #   - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres

  frontend:
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
      # - "80:80"

  nginx:
    image: nginx:1.23
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
