services:

  db:
    image: postgres:15.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  # app:
  #   build:
  #     context: ./team_generator
  #     target: development
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./team_generator:/code
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DEBUG=True
  #     - ADMIN_USERNAME=admin
  #     - ADMIN_PASSWORD=admin

  # nginx:
  #   image: nginx:1.23
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - "80:80"
